#ifndef _COSMIC_BNO_H
#define _COSMIC_BNO_H

#include <stm32f4xx.h>
#include "../../stm32/f4/i2c/i2c.c"

#define BNO_ADDR    ()

// Page 1 
#define BNO_MAG_RADIUS_MSB      (0x6A)
#define BNO_MAG_RADIUS_LSB      (0x69)
#define BNO_ACC_RADIUS_MSB      (0x68)
#define BNO_ACC_RADIUS_LSB      (0x67)
#define BNO_GYR_OFFSET_Z_MSB    (0x66)
#define BNO_GYR_OFFSET_Z_LSB    (0x65)
#define BNO_GYR_OFFSET_Y_MSB    (0x64)
#define BNO_GYR_OFFSET_Y_LSB    (0x63)
#define BNO_GYR_OFFSET_X_MSB    (0x62)
#define BNO_GYR_OFFSET_X_LSB    (0x61)
#define BNO_MAG_OFFSET_Z_MSB    (0x60)
#define BNO_MAG_OFFSET_Z_LSB    (0x5F)
#define BNO_MAG_OFFSET_Y_MSB    (0x5E)
#define BNO_MAG_OFFSET_Y_LSB    (0x5D)
#define BNO_MAG_OFFSET_X_MSB    (0x5C)
#define BNO_MAG_OFFSET_X_LSB    (0x5B)
#define BNO_ACC_OFFSET_Z_MSB    (0x5A)
#define BNO_ACC_OFFSET_Z_LSB    (0x59)
#define BNO_ACC_OFFSET_Y_MSB    (0x58)
#define BNO_ACC_OFFSET_Y_LSB    (0x57)
#define BNO_ACC_OFFSET_X_MSB    (0x56)
#define BNO_ACC_OFFSET_X_LSB    (0x55)
#define BNO_AXIS_MAP_SIGN       (0x42)
#define BNO_AXIS_MAP_CONFIG     (0x41)
#define BNO_TEMP_SOURCE         (0x40)
#define BNO_SYS_TRIGGER         (0x3F)
#define BNO_PWR_MODE            (0x3E)
#define BNO_OPR_MODE            (0x3D)
#define BNO_UNIT_SEL            (0x3B)
#define BNO_SYS_ERR             (0x3A)
#define BNO_SYS_STATUS          (0x39)
#define BNO_SYS_CLK_STATUS      (0x38)
#define BNO_INT_STA             (0x37)
#define BNO_ST_RESULT           (0x36)
#define BNO_CALIB_STAT          (0x35)
#define BNO_TEMP                (0x34)
#define BNO_GRV_DATA_Z_MSB      (0x33)
#define BNO_GRV_DATA_Z_LSB      (0x32)
#define BNO_GRV_DATA_Y_MSB      (0x31)
#define BNO_GRV_DATA_Y_LSB      (0x30)
#define BNO_GRV_DATA_X_MSB      (0x2F)
#define BNO_GRV_DATA_X_LSB      (0x2E)
#define BNO_LIA_DATA_Z_MSB      (0x2D)
#define BNO_LIA_DATA_Z_LSB      (0x2C)
#define BNO_LIA_DATA_Y_MSB      (0x2B)
#define BNO_LIA_DATA_Y_LSB      (0x2A)
#define BNO_LIA_DATA_X_MSB      (0x29)
#define BNO_LIA_DATA_X_LSB      (0x28)
#define BNO_QUA_DATA_Z_MSB      (0x27)
#define BNO_QUA_DATA_Z_LSB      (0x26)
#define BNO_QUA_DATA_Y_MSB      (0x25)
#define BNO_QUA_DATA_Y_LSB      (0x24)
#define BNO_QUA_DATA_X_MSB      (0x23)
#define BNO_QUA_DATA_X_LSB      (0x22)
#define BNO_QUA_DATA_W_MSB      (0x21)
#define BNO_QUA_DATA_W_LSB      (0x20)
#define BNO_EUL_PITCH_MSB       (0x1F)
#define BNO_EUL_PITCH_LSB       (0x1E)
#define BNO_EUL_ROLL_MSB        (0x1D)
#define BNO_EUL_ROLL_LSB        (0x1C)
#define BNO_EUL_HEADING_MSB     (0x1B)
#define BNO_EUL_HEADING_LSB     (0x1A)
#define BNO_GYR_DATA_Z_MSB      (0x19)
#define BNO_GYR_DATA_Z_LSB      (0x18)
#define BNO_GYR_DATA_Y_MSB      (0x17)
#define BNO_GYR_DATA_Y_LSB      (0x16)
#define BNO_GYR_DATA_X_MSB      (0x15)
#define BNO_GYR_DATA_X_LSB      (0x14)
#define BNO_MAG_DATA_Z_MSB      (0x13)
#define BNO_MAG_DATA_Z_LSB      (0x12)
#define BNO_MAG_DATA_Y_MSB      (0x11)
#define BNO_MAG_DATA_Y_LSB      (0x10)
#define BNO_MAG_DATA_X_MSB      (0x0F)
#define BNO_MAG_DATA_X_LSB      (0x0E)
#define BNO_ACC_DATA_Z_MSB      (0x0D)
#define BNO_ACC_DATA_Z_LSB      (0x0C)
#define BNO_ACC_DATA_Y_MSB      (0x0B)
#define BNO_ACC_DATA_Y_LSB      (0x0A)
#define BNO_ACC_DATA_X_MSB      (0x09)
#define BNO_ACC_DATA_X_LSB      (0x08)
#define BNO_PAGE_ID             (0x07)
#define BNO_BL_REV_ID           (0x06)
#define BNO_SW_REV_ID_MSB       (0x05)
#define BNO_SW_REV_ID_LSB       (0x04)
#define BNO_GYR_ID              (0x03)
#define BNO_MAG_ID              (0x02)
#define BNO_ACC_ID              (0x01)
#define BNO_CHIP_ID             (0x00)


typedef struct bno {
    I2C_port *i2c; 
} bno_t;


#endif
